version: '3.8'

services:
    example-webserver:
        container_name: example-nginx
        image: nginx:1.24.0
        ports: ["80:80"]
        volumes:
            - ./app:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    example-php:
        container_name: example-php
        image: php:8.3-fpm
        volumes:
            - ./app:/var/www/project

    example-mysql:
        container_name: example-mysql
        image: mysql:8
        ports: ["3306:3306"]
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - ../docker/example/mysql-data:/var/lib/mysql